# generated by datamodel-codegen:
#   filename:  plan.json
#   timestamp: 2026-08-20T21:42:02+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr


class Tactic(Enum):
    SWITCH_PLAY = 'SWITCH_PLAY'
    OVERLAP = 'OVERLAP'
    UNDERLAP = 'UNDERLAP'
    THIRD_MAN_RUN = 'THIRD_MAN_RUN'
    WALL_PASS = 'WALL_PASS'
    COUNTER_ATTACK = 'COUNTER_ATTACK'
    COUNTER_PRESS = 'COUNTER_PRESS'
    CREATE_WIDTH = 'CREATE_WIDTH'
    BREAK_LINE = 'BREAK_LINE'
    OVERLOAD = 'OVERLOAD'
    ISOLATE_WINGER = 'ISOLATE_WINGER'
    PRESSING_TRAP = 'PRESSING_TRAP'


class Level(Enum):
    LEVEL1_NOVICE = 'LEVEL1_NOVICE'
    LEVEL2_BEGINNER = 'LEVEL2_BEGINNER'
    LEVEL3_INTERMEDIATE = 'LEVEL3_INTERMEDIATE'
    LEVEL4_ADVANCED = 'LEVEL4_ADVANCED'
    LEVEL5_EXPERT = 'LEVEL5_EXPERT'


class Phase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z]+(-[a-z]+)*$') = Field(
        ..., description='Unique identifier for this phase.', title='Phase Identifier'
    )
    name: str = Field(
        ..., description='Short descriptive name for the phase.', title='Phase Name'
    )
    goal: str = Field(
        ...,
        description='What tactical outcome this phase should achieve.',
        title='Phase Goal',
    )


class FootballTacticalPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tactic: Tactic = Field(
        ...,
        description='The tactical concept being demonstrated.',
        title='Tactical Concept',
    )
    level: Level = Field(
        ...,
        description='The experience level for which this plan is intended.',
        title='Level',
    )
    objective: str = Field(
        ...,
        description='A concise statement describing what the play is intended to achieve.',
        title='Coaching Objective',
    )
    formation: str = Field(
        ...,
        description="The attacking team's starting formation.",
        examples=['4-3-3', '4-2-3-1', '3-4-3'],
        title='Attacking Formation',
    )
    phases: list[Phase] = Field(
        ...,
        description='Ordered phases that collectively demonstrate the tactic.',
        min_length=1,
        title='Tactical Phases',
    )
