# generated by datamodel-codegen:
#   filename:  scenario.json
#   timestamp: 2026-08-20T21:42:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class ZonePosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lane_offset: confloat(ge=-1.0, le=1.0) | None = Field(
        None,
        description='Lateral position within the zone. Negative values move toward the left side of the zone and positive values move toward the right side.',
        title='Lane Offset',
    )
    depth_offset: confloat(ge=-1.0, le=1.0) | None = Field(
        None,
        description='Position along the attacking direction within the zone. Negative values move toward the defending goal and positive values move toward the attacking goal.',
        title='Depth Offset',
    )


class OverlapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['OVERLAP']
    runner: str
    outside_player: str


class UnderlapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['UNDERLAP']
    runner: str
    outside_player: str


class CheckToBallAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['CHECK_TO_BALL']
    player: str


class ThirdManRunAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['THIRD_MAN_RUN']
    runner: str


class PressAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['PRESS']
    player: str
    target_player: str


class Direction(Enum):
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    FORWARD = 'FORWARD'
    BACKWARD = 'BACKWARD'


class ShiftAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['SHIFT']
    direction: Direction


class MarkAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['MARK']
    defender: str
    attacker: str


class TrackRunnerAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['TRACK_RUNNER']
    defender: str
    runner: str


class DropAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['DROP']
    player: str


class Tactic(Enum):
    SWITCH_PLAY = 'SWITCH_PLAY'
    OVERLAP = 'OVERLAP'
    UNDERLAP = 'UNDERLAP'
    THIRD_MAN_RUN = 'THIRD_MAN_RUN'
    WALL_PASS = 'WALL_PASS'
    COUNTER_ATTACK = 'COUNTER_ATTACK'
    COUNTER_PRESS = 'COUNTER_PRESS'
    CREATE_WIDTH = 'CREATE_WIDTH'
    BREAK_LINE = 'BREAK_LINE'
    OVERLOAD = 'OVERLOAD'
    ISOLATE_WINGER = 'ISOLATE_WINGER'
    PRESSING_TRAP = 'PRESSING_TRAP'


class Difficulty(Enum):
    LEVEL1_NOVICE = 'LEVEL1_NOVICE'
    LEVEL2_BEGINNER = 'LEVEL2_BEGINNER'
    LEVEL3_INTERMEDIATE = 'LEVEL3_INTERMEDIATE'
    LEVEL4_ADVANCED = 'LEVEL4_ADVANCED'
    LEVEL5_EXPERT = 'LEVEL5_EXPERT'


class PlayDirection(Enum):
    BOTTOM_TO_TOP = 'BOTTOM_TO_TOP'
    TOP_TO_BOTTOM = 'TOP_TO_BOTTOM'
    LEFT_TO_RIGHT = 'LEFT_TO_RIGHT'
    RIGHT_TO_LEFT = 'RIGHT_TO_LEFT'


class TeamType(Enum):
    ATTACK = 'ATTACK'
    DEFEND = 'DEFEND'


class Role(Enum):
    GK = 'GK'
    LB = 'LB'
    LCB = 'LCB'
    CB = 'CB'
    RCB = 'RCB'
    RB = 'RB'
    LWB = 'LWB'
    RWB = 'RWB'
    DM = 'DM'
    LCM = 'LCM'
    CM = 'CM'
    RCM = 'RCM'
    CAM = 'CAM'
    LW = 'LW'
    RW = 'RW'
    LIF = 'LIF'
    RIF = 'RIF'
    ST = 'ST'


class Zone(Enum):
    DEF_LEFT_CORNER = 'DEF_LEFT_CORNER'
    DEF_LEFT_WING = 'DEF_LEFT_WING'
    DEF_LEFT_HALFSPACE = 'DEF_LEFT_HALFSPACE'
    DEF_LEFT_CHANNEL = 'DEF_LEFT_CHANNEL'
    DEF_CENTER_LEFT = 'DEF_CENTER_LEFT'
    DEF_CENTER = 'DEF_CENTER'
    DEF_CENTER_RIGHT = 'DEF_CENTER_RIGHT'
    DEF_RIGHT_CHANNEL = 'DEF_RIGHT_CHANNEL'
    DEF_RIGHT_HALFSPACE = 'DEF_RIGHT_HALFSPACE'
    DEF_RIGHT_WING = 'DEF_RIGHT_WING'
    DEF_RIGHT_CORNER = 'DEF_RIGHT_CORNER'
    MID_LEFT_TOUCHLINE = 'MID_LEFT_TOUCHLINE'
    MID_LEFT_WING = 'MID_LEFT_WING'
    MID_LEFT_HALFSPACE = 'MID_LEFT_HALFSPACE'
    MID_LEFT_CHANNEL = 'MID_LEFT_CHANNEL'
    MID_CENTER_LEFT = 'MID_CENTER_LEFT'
    MID_CENTER = 'MID_CENTER'
    MID_CENTER_RIGHT = 'MID_CENTER_RIGHT'
    MID_RIGHT_CHANNEL = 'MID_RIGHT_CHANNEL'
    MID_RIGHT_HALFSPACE = 'MID_RIGHT_HALFSPACE'
    MID_RIGHT_WING = 'MID_RIGHT_WING'
    MID_RIGHT_TOUCHLINE = 'MID_RIGHT_TOUCHLINE'
    ATT_LEFT_CORNER = 'ATT_LEFT_CORNER'
    ATT_LEFT_WING = 'ATT_LEFT_WING'
    ATT_LEFT_HALFSPACE = 'ATT_LEFT_HALFSPACE'
    ATT_LEFT_CHANNEL = 'ATT_LEFT_CHANNEL'
    ATT_ZONE14_LEFT = 'ATT_ZONE14_LEFT'
    ATT_ZONE14 = 'ATT_ZONE14'
    ATT_ZONE14_RIGHT = 'ATT_ZONE14_RIGHT'
    ATT_RIGHT_CHANNEL = 'ATT_RIGHT_CHANNEL'
    ATT_RIGHT_HALFSPACE = 'ATT_RIGHT_HALFSPACE'
    ATT_RIGHT_WING = 'ATT_RIGHT_WING'
    ATT_RIGHT_CORNER = 'ATT_RIGHT_CORNER'
    LEFT_BOX = 'LEFT_BOX'
    CENTER_BOX = 'CENTER_BOX'
    RIGHT_BOX = 'RIGHT_BOX'
    PENALTY_SPOT = 'PENALTY_SPOT'
    SIX_YARD_BOX = 'SIX_YARD_BOX'


class TacticalPurpose(Enum):
    CREATE_WIDTH = 'CREATE_WIDTH'
    ATTRACT_PRESSURE = 'ATTRACT_PRESSURE'
    SWITCH_PLAY = 'SWITCH_PLAY'
    BREAK_LINE = 'BREAK_LINE'
    CREATE_ISOLATION = 'CREATE_ISOLATION'
    CREATE_NUMERICAL_ADVANTAGE = 'CREATE_NUMERICAL_ADVANTAGE'
    CREATE_POSITIONAL_ADVANTAGE = 'CREATE_POSITIONAL_ADVANTAGE'
    THIRD_MAN_COMBINATION = 'THIRD_MAN_COMBINATION'
    ATTACK_SPACE = 'ATTACK_SPACE'
    PROGRESS_POSSESSION = 'PROGRESS_POSSESSION'
    CREATE_SHOOTING_OPPORTUNITY = 'CREATE_SHOOTING_OPPORTUNITY'
    CREATE_CROSSING_OPPORTUNITY = 'CREATE_CROSSING_OPPORTUNITY'


class TacticalInstruction(Enum):
    HOLD_WIDTH = 'HOLD_WIDTH'
    STAY_HIGH = 'STAY_HIGH'
    DROP_BETWEEN_LINES = 'DROP_BETWEEN_LINES'
    PIN_DEFENDER = 'PIN_DEFENDER'
    ATTACK_SPACE = 'ATTACK_SPACE'
    PROVIDE_SUPPORT = 'PROVIDE_SUPPORT'
    OVERLAP = 'OVERLAP'
    UNDERLAP = 'UNDERLAP'
    ARRIVE_LATE_IN_BOX = 'ARRIVE_LATE_IN_BOX'
    CHECK_TO_BALL = 'CHECK_TO_BALL'


class DefensiveResponse(Enum):
    SHIFT_LEFT = 'SHIFT_LEFT'
    SHIFT_RIGHT = 'SHIFT_RIGHT'
    STEP_FORWARD = 'STEP_FORWARD'
    DROP_DEEPER = 'DROP_DEEPER'
    DOUBLE_TEAM = 'DOUBLE_TEAM'
    TRACK_RUNNER = 'TRACK_RUNNER'
    PRESS_BALL = 'PRESS_BALL'
    PROTECT_CENTER = 'PROTECT_CENTER'


class AdvantageType(Enum):
    NUMERICAL_ADVANTAGE = 'NUMERICAL_ADVANTAGE'
    POSITIONAL_ADVANTAGE = 'POSITIONAL_ADVANTAGE'
    ISOLATION = 'ISOLATION'
    WEAK_SIDE_ACCESS = 'WEAK_SIDE_ACCESS'
    LINE_BREAK = 'LINE_BREAK'
    SPACE_CREATED = 'SPACE_CREATED'
    SHOT_OPPORTUNITY = 'SHOT_OPPORTUNITY'


class OutcomeType(Enum):
    BALL_CHANGES_FLANK = 'BALL_CHANGES_FLANK'
    DEFENSIVE_BLOCK_SHIFTS = 'DEFENSIVE_BLOCK_SHIFTS'
    WEAK_SIDE_RECEIVER_AVAILABLE = 'WEAK_SIDE_RECEIVER_AVAILABLE'
    ISOLATION_CREATED = 'ISOLATION_CREATED'
    LINE_BROKEN = 'LINE_BROKEN'
    SHOT_CREATED = 'SHOT_CREATED'
    CROSS_CREATED = 'CROSS_CREATED'


class Outcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: OutcomeType
    description: str | None = None


class Advantage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: AdvantageType
    zone: Zone | None = None
    player: str | None = None
    description: str | None = None


class BlockHeight(Enum):
    HIGH_PRESS = 'HIGH_PRESS'
    MID_BLOCK = 'MID_BLOCK'
    LOW_BLOCK = 'LOW_BLOCK'


class BlockCompactness(Enum):
    COMPACT = 'COMPACT'
    NORMAL = 'NORMAL'
    STRETCHED = 'STRETCHED'


class PressureLevel(Enum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., description='Human-readable title.', title='Scenario Title')
    tactic: Tactic
    objective: str = Field(
        ..., description='Coaching objective being demonstrated.', title='Objective'
    )
    difficulty: Difficulty
    play_direction: PlayDirection


class Player(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z]+(-[a-z]+)*$') = Field(..., title='Player Identifier')
    role: Role
    team: TeamType
    starting_zone: Zone
    starting_position: ZonePosition | None = None
    tactical_instructions: list[TacticalInstruction] | None = None


class DefensiveBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: BlockHeight
    compactness: BlockCompactness
    pressure_level: PressureLevel


class Phase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z]+(-[a-z]+)*$')
    name: str
    attacking_goal: str
    expected_defensive_response: DefensiveResponse | None = None
    success_condition: str


class PassAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['PASS']
    from_player: str
    to_player: str
    from_zone: Zone
    to_zone: Zone


class DribbleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['DRIBBLE']
    player: str
    from_zone: Zone
    to_zone: Zone


class MoveAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['MOVE']
    player: str
    from_zone: Zone
    to_zone: Zone


class RunAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['RUN']
    player: str
    from_zone: Zone
    to_zone: Zone


class CrossAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['CROSS']
    from_player: str
    target_zone: Zone


class ShotAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['SHOT']
    player: str
    shot_zone: Zone


class Team(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    formation: str
    players: list[Player] = Field(..., min_length=1)


class GameState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ball_owner: str = Field(
        ..., description='Player currently in possession.', title='Ball Owner'
    )
    ball_zone: Zone
    defensive_block: DefensiveBlock


class Plan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phases: list[Phase] = Field(..., min_length=1)


class Action(
    RootModel[
        PassAction
        | DribbleAction
        | MoveAction
        | RunAction
        | OverlapAction
        | UnderlapAction
        | CheckToBallAction
        | ThirdManRunAction
        | CrossAction
        | ShotAction
        | PressAction
        | ShiftAction
        | MarkAction
        | TrackRunnerAction
        | DropAction
    ]
):
    root: (
        PassAction
        | DribbleAction
        | MoveAction
        | RunAction
        | OverlapAction
        | UnderlapAction
        | CheckToBallAction
        | ThirdManRunAction
        | CrossAction
        | ShotAction
        | PressAction
        | ShiftAction
        | MarkAction
        | TrackRunnerAction
        | DropAction
    ) = Field(
        ..., description='Strongly typed football action.', title='Football Action'
    )


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: str
    sequence: int
    phase_id: str
    action: Action
    tactical_purpose: TacticalPurpose
    advantages_created: list[Advantage] | None = None
    tactical_explanation: str | None = None


class FootballTacticalScenario(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    attacking_team: Team
    defending_team: Team
    initial_state: GameState
    plan: Plan
    events: list[Event] = Field(
        ...,
        description='Ordered football actions that collectively form the tactical sequence.',
        min_length=1,
        title='Event Timeline',
    )
    expected_outcomes: list[Outcome]
    coaching_notes: list[str] | None = None
