# generated by datamodel-codegen:
#   filename:  scenario.json
#   timestamp: 2026-09-16T13:00:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class ZonePosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lane_offset: confloat(ge=-1.0, le=1.0) | None = Field(
        None,
        description="Lateral position within the zone. Negative values move toward the attacking team's left side; positive values move toward its right side. The frame of reference is the attacking team facing the goal it is attacking, independent of how the renderer displays the pitch.",
        title='Lane Offset',
    )
    depth_offset: confloat(ge=-1.0, le=1.0) | None = Field(
        None,
        description="Position along the attacking direction within the zone. Negative values move toward the attacking team's own goal; positive values move toward the goal being attacked.",
        title='Depth Offset',
    )


class PressAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['PRESS']
    player: str = Field(..., description='Defending player applying pressure.')
    target_player: str = Field(..., description='Player being pressed.')
    pressing_distance: PositiveFloat = Field(
        ...,
        description="Normalized pitch-distance from the target player at the end of the press. 1.0 equals the full pitch length. The presser approaches the target and finishes pressing_distance away from the target along the line from the presser's starting position toward the target. This prevents the renderer from having to invent a stopping distance.",
    )


class Direction(Enum):
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    FORWARD = 'FORWARD'
    BACKWARD = 'BACKWARD'


class ShiftAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['SHIFT']
    direction: Direction = Field(
        ...,
        description="Direction relative to the attacking team's perspective. LEFT and RIGHT are lateral from the attacking team facing its attacking goal. FORWARD means toward the goal being attacked; BACKWARD means toward the attacking team's own goal.",
    )
    distance: PositiveFloat = Field(
        ...,
        description='Normalized translation magnitude. For LEFT/RIGHT, 1.0 equals the full pitch width; for FORWARD/BACKWARD, 1.0 equals the full pitch length.',
    )


class MarkAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['MARK']
    defender: str
    attacker: str
    goal_side_distance: PositiveFloat = Field(
        ...,
        description="Normalized pitch-distance between defender and attacker at the end of the marking action. 1.0 equals the full pitch length. The defender takes a position goal-side of the attacker, where goal-side means toward the defending team's own goal.",
    )


class TrackRunnerAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['TRACK_RUNNER']
    defender: str
    runner: str
    tracking_distance: PositiveFloat = Field(
        ...,
        description='Normalized pitch-distance maintained between defender and runner while tracking. 1.0 equals the full pitch length.',
    )


class Tactic(Enum):
    SWITCH_PLAY = 'SWITCH_PLAY'
    OVERLAP = 'OVERLAP'
    UNDERLAP = 'UNDERLAP'
    THIRD_MAN_RUN = 'THIRD_MAN_RUN'
    WALL_PASS = 'WALL_PASS'
    COUNTER_ATTACK = 'COUNTER_ATTACK'
    COUNTER_PRESS = 'COUNTER_PRESS'
    CREATE_WIDTH = 'CREATE_WIDTH'
    BREAK_LINE = 'BREAK_LINE'
    OVERLOAD = 'OVERLOAD'
    ISOLATE_WINGER = 'ISOLATE_WINGER'
    PRESSING_TRAP = 'PRESSING_TRAP'


class Difficulty(Enum):
    LEVEL1_NOVICE = 'LEVEL1_NOVICE'
    LEVEL2_BEGINNER = 'LEVEL2_BEGINNER'
    LEVEL3_INTERMEDIATE = 'LEVEL3_INTERMEDIATE'
    LEVEL4_ADVANCED = 'LEVEL4_ADVANCED'
    LEVEL5_EXPERT = 'LEVEL5_EXPERT'


class PlayDirection(Enum):
    BOTTOM_TO_TOP = 'BOTTOM_TO_TOP'
    TOP_TO_BOTTOM = 'TOP_TO_BOTTOM'
    LEFT_TO_RIGHT = 'LEFT_TO_RIGHT'
    RIGHT_TO_LEFT = 'RIGHT_TO_LEFT'


class TeamType(Enum):
    ATTACK = 'ATTACK'
    DEFEND = 'DEFEND'


class Role(Enum):
    GK = 'GK'
    LB = 'LB'
    LCB = 'LCB'
    CB = 'CB'
    RCB = 'RCB'
    RB = 'RB'
    LWB = 'LWB'
    RWB = 'RWB'
    DM = 'DM'
    LCM = 'LCM'
    CM = 'CM'
    RCM = 'RCM'
    CAM = 'CAM'
    LW = 'LW'
    RW = 'RW'
    LIF = 'LIF'
    RIF = 'RIF'
    ST = 'ST'


class Zone(Enum):
    DEF_LEFT_CORNER = 'DEF_LEFT_CORNER'
    DEF_LEFT_WING = 'DEF_LEFT_WING'
    DEF_LEFT_HALFSPACE = 'DEF_LEFT_HALFSPACE'
    DEF_LEFT_CHANNEL = 'DEF_LEFT_CHANNEL'
    DEF_CENTER_LEFT = 'DEF_CENTER_LEFT'
    DEF_CENTER = 'DEF_CENTER'
    DEF_CENTER_RIGHT = 'DEF_CENTER_RIGHT'
    DEF_RIGHT_CHANNEL = 'DEF_RIGHT_CHANNEL'
    DEF_RIGHT_HALFSPACE = 'DEF_RIGHT_HALFSPACE'
    DEF_RIGHT_WING = 'DEF_RIGHT_WING'
    DEF_RIGHT_CORNER = 'DEF_RIGHT_CORNER'
    MID_LEFT_TOUCHLINE = 'MID_LEFT_TOUCHLINE'
    MID_LEFT_WING = 'MID_LEFT_WING'
    MID_LEFT_HALFSPACE = 'MID_LEFT_HALFSPACE'
    MID_LEFT_CHANNEL = 'MID_LEFT_CHANNEL'
    MID_CENTER_LEFT = 'MID_CENTER_LEFT'
    MID_CENTER = 'MID_CENTER'
    MID_CENTER_RIGHT = 'MID_CENTER_RIGHT'
    MID_RIGHT_CHANNEL = 'MID_RIGHT_CHANNEL'
    MID_RIGHT_HALFSPACE = 'MID_RIGHT_HALFSPACE'
    MID_RIGHT_WING = 'MID_RIGHT_WING'
    MID_RIGHT_TOUCHLINE = 'MID_RIGHT_TOUCHLINE'
    ATT_LEFT_CORNER = 'ATT_LEFT_CORNER'
    ATT_LEFT_WING = 'ATT_LEFT_WING'
    ATT_LEFT_HALFSPACE = 'ATT_LEFT_HALFSPACE'
    ATT_LEFT_CHANNEL = 'ATT_LEFT_CHANNEL'
    ATT_ZONE14_LEFT = 'ATT_ZONE14_LEFT'
    ATT_ZONE14 = 'ATT_ZONE14'
    ATT_ZONE14_RIGHT = 'ATT_ZONE14_RIGHT'
    ATT_RIGHT_CHANNEL = 'ATT_RIGHT_CHANNEL'
    ATT_RIGHT_HALFSPACE = 'ATT_RIGHT_HALFSPACE'
    ATT_RIGHT_WING = 'ATT_RIGHT_WING'
    ATT_RIGHT_CORNER = 'ATT_RIGHT_CORNER'
    LEFT_BOX = 'LEFT_BOX'
    CENTER_BOX = 'CENTER_BOX'
    RIGHT_BOX = 'RIGHT_BOX'
    PENALTY_SPOT = 'PENALTY_SPOT'
    SIX_YARD_BOX = 'SIX_YARD_BOX'


class TacticalPurpose(Enum):
    CREATE_WIDTH = 'CREATE_WIDTH'
    ATTRACT_PRESSURE = 'ATTRACT_PRESSURE'
    SWITCH_PLAY = 'SWITCH_PLAY'
    BREAK_LINE = 'BREAK_LINE'
    CREATE_ISOLATION = 'CREATE_ISOLATION'
    CREATE_NUMERICAL_ADVANTAGE = 'CREATE_NUMERICAL_ADVANTAGE'
    CREATE_POSITIONAL_ADVANTAGE = 'CREATE_POSITIONAL_ADVANTAGE'
    THIRD_MAN_COMBINATION = 'THIRD_MAN_COMBINATION'
    ATTACK_SPACE = 'ATTACK_SPACE'
    PROGRESS_POSSESSION = 'PROGRESS_POSSESSION'
    CREATE_SHOOTING_OPPORTUNITY = 'CREATE_SHOOTING_OPPORTUNITY'
    CREATE_CROSSING_OPPORTUNITY = 'CREATE_CROSSING_OPPORTUNITY'


class TacticalInstruction(Enum):
    HOLD_WIDTH = 'HOLD_WIDTH'
    STAY_HIGH = 'STAY_HIGH'
    DROP_BETWEEN_LINES = 'DROP_BETWEEN_LINES'
    PIN_DEFENDER = 'PIN_DEFENDER'
    ATTACK_SPACE = 'ATTACK_SPACE'
    PROVIDE_SUPPORT = 'PROVIDE_SUPPORT'
    OVERLAP = 'OVERLAP'
    UNDERLAP = 'UNDERLAP'
    ARRIVE_LATE_IN_BOX = 'ARRIVE_LATE_IN_BOX'
    CHECK_TO_BALL = 'CHECK_TO_BALL'


class DefensiveResponse(Enum):
    SHIFT_LEFT = 'SHIFT_LEFT'
    SHIFT_RIGHT = 'SHIFT_RIGHT'
    STEP_FORWARD = 'STEP_FORWARD'
    DROP_DEEPER = 'DROP_DEEPER'
    DOUBLE_TEAM = 'DOUBLE_TEAM'
    TRACK_RUNNER = 'TRACK_RUNNER'
    PRESS_BALL = 'PRESS_BALL'
    PROTECT_CENTER = 'PROTECT_CENTER'


class AdvantageType(Enum):
    NUMERICAL_ADVANTAGE = 'NUMERICAL_ADVANTAGE'
    POSITIONAL_ADVANTAGE = 'POSITIONAL_ADVANTAGE'
    ISOLATION = 'ISOLATION'
    WEAK_SIDE_ACCESS = 'WEAK_SIDE_ACCESS'
    LINE_BREAK = 'LINE_BREAK'
    SPACE_CREATED = 'SPACE_CREATED'
    SHOT_OPPORTUNITY = 'SHOT_OPPORTUNITY'


class OutcomeType(Enum):
    BALL_CHANGES_FLANK = 'BALL_CHANGES_FLANK'
    DEFENSIVE_BLOCK_SHIFTS = 'DEFENSIVE_BLOCK_SHIFTS'
    WEAK_SIDE_RECEIVER_AVAILABLE = 'WEAK_SIDE_RECEIVER_AVAILABLE'
    ISOLATION_CREATED = 'ISOLATION_CREATED'
    LINE_BROKEN = 'LINE_BROKEN'
    SHOT_CREATED = 'SHOT_CREATED'
    CROSS_CREATED = 'CROSS_CREATED'


class Outcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: OutcomeType
    description: str | None = Field(
        None,
        description='Human-facing explanation of the guaranteed end-state assertion. It is not load-bearing.',
    )


class Advantage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: AdvantageType
    zone: Zone | None = Field(
        None,
        description="Specific zone to which the advantage applies. If omitted, the advantage has no specific spatial locus and must not be rendered as belonging to the current ball zone or any player's zone by default.",
    )
    player: str | None = Field(
        None,
        description='Specific player who benefits from the advantage. If omitted, the advantage is not attributed to a particular player.',
    )
    description: str | None = Field(
        None, description='Human-facing explanation. It is not load-bearing.'
    )


class BlockHeight(Enum):
    HIGH_PRESS = 'HIGH_PRESS'
    MID_BLOCK = 'MID_BLOCK'
    LOW_BLOCK = 'LOW_BLOCK'


class BlockCompactness(Enum):
    COMPACT = 'COMPACT'
    NORMAL = 'NORMAL'
    STRETCHED = 'STRETCHED'


class PressureLevel(Enum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class BallState(Enum):
    CONTROLLED = 'CONTROLLED'
    LOOSE = 'LOOSE'


class PassTrajectory(Enum):
    GROUND = 'GROUND'
    DRIVEN = 'DRIVEN'
    LOFTED = 'LOFTED'


class CrossTrajectory(Enum):
    DRIVEN_CROSS = 'DRIVEN_CROSS'
    LOFTED_CROSS = 'LOFTED_CROSS'


class ShotTrajectory(Enum):
    GROUND = 'GROUND'
    LOW_AERIAL = 'LOW_AERIAL'
    HIGH_AERIAL = 'HIGH_AERIAL'


class CrossResult(Enum):
    RECEIVED = 'RECEIVED'
    DEFENDED = 'DEFENDED'
    LOOSE = 'LOOSE'
    OUT_OF_PLAY = 'OUT_OF_PLAY'


class ShotResult(Enum):
    GOAL = 'GOAL'
    SAVED = 'SAVED'
    BLOCKED = 'BLOCKED'
    POST = 'POST'
    DEFLECTED = 'DEFLECTED'
    OFF_TARGET = 'OFF_TARGET'
    OUT_OF_PLAY = 'OUT_OF_PLAY'
    LOOSE = 'LOOSE'


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(
        ...,
        description='Human-readable scenario title. This field is explanatory metadata and may be displayed to the learner.',
        title='Scenario Title',
    )
    tactic: Tactic
    objective: str = Field(
        ...,
        description='Human-readable coaching objective. This field is explanatory and is not required to determine the structured tactical classification.',
        title='Objective',
    )
    difficulty: Difficulty
    play_direction: PlayDirection


class Player(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z]+(-[a-z]+)*$') = Field(
        ...,
        description='Globally unique player identifier within the entire scenario, not merely within a team. Because actions reference players by bare ID, duplicate IDs across either team are invalid. IDs must be unique across both attacking_team.players and defending_team.players.',
        title='Player Identifier',
    )
    role: Role
    starting_zone: Zone
    starting_position: ZonePosition | None = None
    tactical_instructions: list[TacticalInstruction] | None = Field(
        None,
        description="Human-readable structured instruction labels describing the player's intended tactical behavior. These instructions are declarative coaching metadata, not additional movement events.",
    )


class DefensiveBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: BlockHeight
    compactness: BlockCompactness
    pressure_level: PressureLevel


class Phase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z]+(-[a-z]+)*$')
    name: str = Field(
        ...,
        description='Learner-safe phase label. This name may be displayed during playback and therefore must not explicitly name or reveal metadata.tactic or an unambiguous synonym for the answer.',
    )
    attacking_goal: str = Field(
        ...,
        description='Human-readable description of the tactical goal of this phase. It is explanatory and is not load-bearing for animation or validation.',
    )
    expected_defensive_response: DefensiveResponse | None = None
    success_condition: str = Field(
        ...,
        description='Human-readable description of the condition that constitutes success for the phase. It is explanatory and must not be parsed as machine-readable state.',
    )


class PassAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['PASS']
    from_player: str = Field(
        ...,
        description="Player making the pass. The player's current zone at event start must equal from_zone. Passing does not move the passer.",
    )
    to_player: str = Field(
        ...,
        description='Intended receiving player. The receiver must be at to_zone when the pass arrives. The receiver may move concurrently with the pass.',
    )
    from_zone: Zone
    to_zone: Zone
    trajectory: PassTrajectory


class DribbleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['DRIBBLE']
    player: str
    from_zone: Zone
    to_zone: Zone
    to_position: ZonePosition | None = None


class MoveAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['MOVE']
    player: str
    from_zone: Zone
    to_zone: Zone
    to_position: ZonePosition | None = None


class RunAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['RUN']
    player: str
    from_zone: Zone
    to_zone: Zone
    to_position: ZonePosition | None = None


class OverlapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['OVERLAP']
    runner: str = Field(..., description='Player making the overlapping run.')
    outside_player: str = Field(
        ..., description='Player outside whom the runner passes.'
    )
    to_zone: Zone
    to_position: ZonePosition | None = None


class UnderlapAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['UNDERLAP']
    runner: str = Field(..., description='Player making the underlapping run.')
    outside_player: str = Field(
        ..., description='Player whose inside/halfspace lane the runner enters.'
    )
    to_zone: Zone
    to_position: ZonePosition | None = None


class CheckToBallAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['CHECK_TO_BALL']
    player: str
    to_zone: Zone
    to_position: ZonePosition | None = None


class ThirdManRunAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['THIRD_MAN_RUN']
    runner: str
    to_zone: Zone
    to_position: ZonePosition | None = None


class CrossAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['CROSS']
    from_player: str
    target_zone: Zone
    target_player: str | None = None
    trajectory: CrossTrajectory
    result: CrossResult


class ShotAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['SHOT']
    player: str
    shot_zone: Zone
    trajectory: ShotTrajectory
    result: ShotResult


class DropAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['DROP']
    player: str
    to_zone: Zone
    to_position: ZonePosition | None = None


class TurnoverAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_type: Literal['TURNOVER']
    winning_team: TeamType
    zone: Zone
    winner: str | None = Field(
        None,
        description='Optional player who wins/recovers possession. If supplied, this player becomes ball_owner when the turnover completes.',
    )


class Team(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    formation: str = Field(
        ...,
        description="Human-readable formation notation, such as 4-3-3. Formation is descriptive metadata; the actual starting player locations are determined by each player's starting_zone and optional starting_position.",
    )
    players: list[Player] = Field(..., min_length=1)


class GameState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ball_owner: str | None = Field(
        ...,
        description="Player currently controlling the ball. Required when ball_state is CONTROLLED and null when ball_state is LOOSE. A controlled ball must be located in the owner's current position/zone; ball_zone is not an independent authoritative position for a controlled ball.",
        title='Ball Owner',
    )
    ball_zone: Zone
    ball_state: BallState
    defensive_block: DefensiveBlock


class Plan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phases: list[Phase] = Field(..., min_length=1)


class Action(
    RootModel[
        PassAction
        | DribbleAction
        | MoveAction
        | RunAction
        | OverlapAction
        | UnderlapAction
        | CheckToBallAction
        | ThirdManRunAction
        | CrossAction
        | ShotAction
        | PressAction
        | ShiftAction
        | MarkAction
        | TrackRunnerAction
        | DropAction
        | TurnoverAction
    ]
):
    root: (
        PassAction
        | DribbleAction
        | MoveAction
        | RunAction
        | OverlapAction
        | UnderlapAction
        | CheckToBallAction
        | ThirdManRunAction
        | CrossAction
        | ShotAction
        | PressAction
        | ShiftAction
        | MarkAction
        | TrackRunnerAction
        | DropAction
        | TurnoverAction
    ) = Field(
        ...,
        description="Strongly typed football action. Every action that changes a player's spatial state provides an explicit destination or a normative derivation rule. Player movement between explicit zones is rendered as continuous linear interpolation at constant speed over the event duration unless a tracking action specifies otherwise.",
        title='Football Action',
    )


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: str = Field(
        ..., description='Unique identifier for this event within the scenario.'
    )
    sequence: conint(ge=1) = Field(
        ...,
        description="1-based position of this event in the events array. Sequence is required to equal the event's array index plus one. It is not a time value and does not establish concurrency. Array order is authoritative.",
    )
    phase_id: str = Field(
        ...,
        description='ID of the phase to which this event belongs. It must reference a phase.id in plan.phases.',
    )
    start_time: confloat(ge=0.0) = Field(
        ...,
        description='Event start time in seconds from the beginning of the scenario. This is the authoritative timing field. Events with equal start_time begin simultaneously; events whose intervals overlap are concurrent. There is no consumer-derived action timing.',
    )
    duration: PositiveFloat = Field(
        ...,
        description='Event duration in seconds. The event occupies the half-open interval [start_time, start_time + duration). Player and ball movement is interpolated continuously throughout this interval unless the action description specifies a following behavior such as TRACK_RUNNER. A gap between events represents a period during which no encoded event occurs; it is not implicitly a tactical pause or ball-holding action.',
    )
    action: Action
    tactical_purpose: TacticalPurpose
    advantages_created: list[Advantage] | None = Field(
        None,
        description='Structured advantages created when this event completes. These are machine-readable tactical annotations, not merely prose.',
    )
    tactical_explanation: str | None = Field(
        None,
        description='Human-facing explanation of why the event matters tactically. It is post-play explanatory material, may name the tactic, and is never required for machine interpretation.',
    )


class FootballTacticalScenario(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    attacking_team: Team
    defending_team: Team
    initial_state: GameState
    plan: Plan
    events: list[Event] = Field(
        ...,
        description='Events are stored in chronological sequence. Array order is authoritative and is represented redundantly by the required 1-based sequence field. Sequence values must be contiguous and equal to their 1-based array positions. Events are not necessarily sequential in time: two or more events may overlap or occur simultaneously when their time intervals overlap or their start_time values are equal.',
        min_length=1,
        title='Event Timeline',
    )
    expected_outcomes: list[Outcome] = Field(
        ...,
        description="Guaranteed end-state assertions for the scenario. An expected outcome is not merely a hoped-for result and is not an assertion about something that may occur transiently during the sequence. If an outcome is not guaranteed by the scenario's structured event stream, it must not be included here.",
    )
    coaching_notes: list[str] | None = Field(
        None,
        description='Human-facing notes intended for a coach or instructor. These are post-play explanatory material and may reveal the tactic or its solution. They are not load-bearing: a consumer must never need to parse them to determine player positions, ball state, timing, tactic, or any other structured fact.',
    )
